// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSwci-JuuPAi3mL9uCwtsM43d1tXBSodE',
    appId: '1:649664055509:web:d38ca49d7cf48350917a5c',
    messagingSenderId: '649664055509',
    projectId: 'premsmsapp',
    authDomain: 'premsmsapp.firebaseapp.com',
    storageBucket: 'premsmsapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcKxD2ECVTXvnPbotPu8omdzzlLPnHzmE',
    appId: '1:649664055509:android:fbea479f8120d1c8917a5c',
    messagingSenderId: '649664055509',
    projectId: 'premsmsapp',
    storageBucket: 'premsmsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBQ-_Z3s_sux9S1yvp3L_SBnBW4BKTHXA',
    appId: '1:649664055509:ios:7f2fccd3b647f961917a5c',
    messagingSenderId: '649664055509',
    projectId: 'premsmsapp',
    storageBucket: 'premsmsapp.appspot.com',
    iosBundleId: 'com.example.jetbulksmsservices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBQ-_Z3s_sux9S1yvp3L_SBnBW4BKTHXA',
    appId: '1:649664055509:ios:7f2fccd3b647f961917a5c',
    messagingSenderId: '649664055509',
    projectId: 'premsmsapp',
    storageBucket: 'premsmsapp.appspot.com',
    iosBundleId: 'com.example.jetbulksmsservices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSwci-JuuPAi3mL9uCwtsM43d1tXBSodE',
    appId: '1:649664055509:web:22e926cb8bbde72b917a5c',
    messagingSenderId: '649664055509',
    projectId: 'premsmsapp',
    authDomain: 'premsmsapp.firebaseapp.com',
    storageBucket: 'premsmsapp.appspot.com',
  );
}
